"""
Licensed under the Apache License, Version 2.0.
See the COPYRIGHT and LICENSE files in the project root for details.

Custom installer for the Azure CLI ("az").

The Azure CLI is a Python application, not a single static binary, so "download
a prebuilt binary" means something different on each platform. This hook walks
the highest rung the platform actually supports and hands everything else back
to task/setup as a declarative install_cmd (see _desc.yaml):

  windows -> TIER 1: the official self-contained x64 ZIP (bundles its own
             CPython), unpacked into the cache. No admin rights.
  darwin  -> TIER 1: the official macos tarball, plus a generated "bin/az"
             wrapper that supplies the AZ_PYTHON the upstream launcher demands.
             Steps down to brew when the host has no matching CPython.
  linux   -> TIER 2/3: no portable download exists upstream, so pick the right
             package-manager command and let task/setup run it.
"""

import os
import re
import shutil

from tool_c393ba5c6fa14f66.api.ctool import InitCTool


# Written over the tarball's "bin/az" symlink on macOS. The upstream launcher
# (libexec/bin/az) hard-fails with "Error: AZ_PYTHON not set." for every install
# that is not a Homebrew cask, so a plain unpack of the tarball is not runnable
# on its own. Resolving the interpreter lazily - "use AZ_PYTHON if the caller
# already exported one, otherwise the one found at install time" - keeps the
# unpacked tree relocatable and keeps an explicit override working.
AZ_MACOS_WRAPPER = '''#!/usr/bin/env bash
# Generated by cMeta tool/az - do not edit.
#
# The Azure CLI macos tarball is not self-contained: its launcher needs
# AZ_PYTHON to point at a CPython __PY_VER__ interpreter. Supply the one that
# was found when this tool was set up, unless the caller exported another.
: "${AZ_PYTHON:=__AZ_PYTHON__}"
export AZ_PYTHON
az_bin_dir="$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
exec "$az_bin_dir/../libexec/bin/az" "$@"
'''


class CTool(InitCTool):
    """
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, module_file_path = __file__, **kwargs)


    ############################################################
    @staticmethod
    def _version_tuple(version):
        """
        Leading numeric components of a version as a comparable tuple.
        "2.89.1" -> (2, 89, 1); anything unparsable -> ().
        """

        parts = []

        for chunk in str(version).split('.'):
            match = re.match(r'^(\d+)', chunk)
            if not match:
                break
            parts.append(int(match.group(1)))

        return tuple(parts)


    ############################################################
    def _too_old(self, version, min_key):
        """
        True when "version" predates the release that first shipped the prebuilt
        asset named by "min_key" in _desc.yaml.
        """

        minimum = self.cdesc.get(min_key)

        if not minimum:
            return False

        detected = self._version_tuple(version)

        return bool(detected) and detected < self._version_tuple(minimum)


    ############################################################
    @staticmethod
    def _find_macos_python(py_ver):
        """
        Locate a CPython "py_ver" (e.g. "3.14") usable as AZ_PYTHON.

        Only version-specific locations are considered - a bare "python3" is
        deliberately ignored, because the launcher derives the site-packages
        path from that exact minor version and a mismatch would import nothing.
        """

        candidates = [os.environ.get('AZ_PYTHON')]

        for prefix in ['/opt/homebrew', '/usr/local']:
            candidates.append(f'{prefix}/opt/python@{py_ver}/libexec/bin/python3')
            candidates.append(f'{prefix}/bin/python{py_ver}')

        candidates.append(f'/Library/Frameworks/Python.framework/Versions/{py_ver}/bin/python3')
        candidates.append(shutil.which(f'python{py_ver}'))

        for candidate in candidates:
            if candidate and os.path.isfile(candidate) and os.access(candidate, os.X_OK):
                return candidate

        return None


    ############################################################
    def _download(self, ctx, params, urls, directory, check_file):
        """
        Hand the mirror list to task/download-file and unpack it in place.
        """

        control = params.get('control', {})

        ii = {'category': 'task,c36be4b9314a45e0',
              'command': 'run',
              'arg1': 'download-file,03fed13e2e0447cf',
              'ctx': ctx,
              'directory': directory,
              'url': urls,
              'env': params.get('env'),
              'timeout': params.get('timeout'),
              'con': control.get('con', False),
              'quiet': control.get('quiet', False),
              'verbose': control.get('verbose', False),
              'unzip': True,
              'clean': True,
              'clean_after_unzip': True,
              # Both archives unpack straight into their root (the ZIP starts at
              # "bin/", the tarball at "./bin/") - there is no wrapper folder.
              'strip_folders': 0,
              'check_file': check_file,
              'make_check_file_executable': True,
        }

        return self.cm.access(ii)


    ############################################################
    def install(self,
                ctx: dict,
                params: dict,
                cmd: str = None,
                *misc: dict,
    ):
        """
        Install the Azure CLI, preferring a prebuilt download where upstream
        publishes one.
        """

        if self.cm.debug:
            self.logger.debug("RUNNING TOOL az api_v1 install")

        ctx_tasks = ctx['tasks']
        _global = ctx_tasks['global']

        uname = _global['host']['os']['uname']
        uarch = _global['host']['os']['uarch']

        version = params.get('version')
        version_simple = params.get('version_simple')

        if not version:
            # Pinned in _desc.yaml so that bumping it needs no code change
            version = self.cdesc['default_version']
            version_simple = version

        control = params.get('control', {})
        con = control.get('con', False)
        verbose = control.get('verbose', False)

        space = '  ' * ctx_tasks['nested_call'] if verbose else ''

        #######################################################################
        # Linux: nothing portable is published upstream - no tarball, no static
        # binary, and the .deb/.rpm both bundle a venv wired to /opt/az that
        # does not survive being moved. Choose the package-manager command here
        # rather than in _desc.yaml, because install_cmd only keys on the OS and
        # apt-based distros need a step the others do not: the azure-cli package
        # lives in a Microsoft repo, so "apt install azure-cli" fails on stock
        # Debian/Ubuntu until that repo and its signing key are added. The
        # Microsoft-maintained script does exactly that, then installs.
        if uname not in ['windows', 'darwin']:
            os_extra = _global['host'].get('os_extra', {})
            package_manager = os_extra.get('package_manager')

            install_cmd = cmd

            if package_manager in ['apt', 'apt-get']:
                install_cmd = ('{{global.curl.qpath}} -sL https://aka.ms/InstallAzureCLIDeb'
                               ' | {{global.host.os_extra.sudo_cmd}}bash')

                if con:
                    print ('')
                    print (f'{space}INFO: using the Microsoft apt repository script for the Azure CLI')

            return {
                'return': 16,
                'error': f'no prebuilt Azure CLI download is published for {uname} - '
                          'using the system package manager instead',
                'install_cmd': install_cmd, # needed to proceed with the main installation routine !
            }

        #######################################################################
        # Windows and macOS both need an exact version to build an asset URL
        if not version_simple:
            return {
                'return': 16,
                'error': f'custom install for az can use only exact/simple versions in "{__file__}"',
                'install_cmd': cmd, # needed to proceed with the main installation routine !
            }

        directory = 'content'
        content_path = os.path.join(os.getcwd(), directory)

        #######################################################################
        if uname == 'windows':
            # Only a 64-bit ZIP is published, and only from 2.57.0 onwards
            if uarch != 'amd64':
                return {
                    'return': 16,
                    'error': f'the Azure CLI ZIP package is published for amd64 only, not {uarch}',
                    'install_cmd': cmd,
                }

            if self._too_old(version_simple, 'min_version_zip'):
                minimum = self.cdesc['min_version_zip']
                return {
                    'return': 16,
                    'error': f'the Azure CLI ZIP package starts at {minimum}, {version_simple} predates it',
                    'install_cmd': cmd,
                }

            filename = f'azure-cli-{version_simple}-x64.zip'
            templates = self.cdesc['download_url_templates_windows']

            # Self-contained: the ZIP carries python.exe and Lib/ next to bin/
            path_to_tool = os.path.join(content_path, 'bin', 'az.cmd')

        #######################################################################
        else:
            uarch2 = {'amd64': 'x86_64', 'arm64': 'arm64'}.get(uarch)

            if not uarch2:
                return {
                    'return': 16,
                    'error': f'no Azure CLI macos tarball is published for {uarch}',
                    'install_cmd': cmd,
                }

            if self._too_old(version_simple, 'min_version_macos_tarball'):
                minimum = self.cdesc['min_version_macos_tarball']
                return {
                    'return': 16,
                    'error': f'the Azure CLI macos tarball starts at {minimum}, {version_simple} predates it',
                    'install_cmd': cmd,
                }

            filename = f'azure-cli-{version_simple}-macos-{uarch2}.tar.gz'
            templates = self.cdesc['download_url_templates_darwin']

            # "bin/az" ships as a relative symlink into libexec; the wrapper
            # written below replaces it once the tree is on disk.
            path_to_tool = os.path.join(content_path, 'bin', 'az')

        #######################################################################
        urls = [t.format(version = version_simple, filename = filename) for t in templates]

        if con:
            print ('')
            print (f'{space}INFO: Current path: {os.getcwd()}')
            for url in urls:
                print (f'{space}INFO: Azure CLI download URL: {url}')
            print (f'{space}INFO: Check file: {path_to_tool}')

        rx = self._download(ctx, params, urls, directory, path_to_tool)
        if self.cm.catch_error(rx): return rx

        #######################################################################
        # macOS only: make the unpacked tree actually runnable
        if uname == 'darwin':
            launcher = os.path.join(content_path, 'libexec', 'bin', 'az')

            if not os.path.isfile(launcher):
                return {
                    'return': 16,
                    'error': f'unexpected Azure CLI tarball layout - "{launcher}" is missing',
                    'install_cmd': cmd,
                }

            # Read the required CPython from the launcher instead of hardcoding
            # it, so a future release moving to another minor version still works
            with open(launcher, 'r', encoding = 'utf-8', errors = 'replace') as f:
                match = re.search(r'^PY_VER\s*=\s*"([\d.]+)"', f.read(), re.MULTILINE)

            py_ver = match.group(1) if match else '3.14'

            python_path = self._find_macos_python(py_ver)

            if not python_path:
                # Leaving the tarball in place would produce an "az" that exits
                # with "AZ_PYTHON not set" on every call. brew pulls the matching
                # CPython in as a dependency, so step down to it instead.
                return {
                    'return': 16,
                    'error': f'the Azure CLI macos tarball needs a CPython {py_ver} interpreter '
                             f'(none found; set AZ_PYTHON or `brew install python@{py_ver}`) - '
                              'installing with brew instead',
                    'install_cmd': cmd,
                }

            if con:
                print ('')
                print (f'{space}INFO: AZ_PYTHON for the Azure CLI launcher: {python_path}')

            wrapper = AZ_MACOS_WRAPPER.replace('__PY_VER__', py_ver)
            wrapper = wrapper.replace('__AZ_PYTHON__', python_path)

            # path_to_tool is the tarball's symlink into libexec - drop it first,
            # otherwise the write would follow the link and clobber the launcher
            if os.path.islink(path_to_tool) or os.path.isfile(path_to_tool):
                os.remove(path_to_tool)

            with open(path_to_tool, 'w', encoding = 'utf-8', newline = '\n') as f:
                f.write(wrapper)

            os.chmod(path_to_tool, 0o755)

        return {
            'return': 0,
            'install_cmd': None,
            'found_path': path_to_tool,
        }
