artifact: 9a28720e29f9444b
authors: Grigori Fursin
base_category_default_api_versions:
  '1': 1
category: category,dd9ea50e7f76467f
copyright: Copyright (C) 2025-2026 Grigori Fursin and cTuning Labs. All rights reserved.
creation_timestamp: '2026-04-20T08:05:13.348995+00:00'
last_api_version: 1

