authors: Grigori Fursin
copyright: Copyright (C) 2025-2026 Grigori Fursin and cTuning Labs. All rights reserved.

names:
  - docker{{global.host.vars.file_ext_exe}}

match_version: 
  - regex: 'version ([\d.]+)'
    group: 1

cmd_get_version: '{{tool_path}} --version'

extra_paths:
  windows:
    - "C:\\Program Files\\Docker\\Docker\\**"
    - "D:\\Program Files\\Docker\\Docker\\**"
  linux:
    - "/usr/local/**"

