redirect_params:
  arg2: uses.test-dummy3-clone-git-repo.url
  url: uses.test-dummy3-clone-git-repo.url
uses:
- alias: test-dummy3-clone-git-repo
  task: clone-git-repo
  task_uid: af9422df6ea241ec
  url: https://github.com/mlcommons/ck
  cache: True
- alias: test-dummy3-clone-git-repo2
  task: clone-git-repo
  task_uid: af9422df6ea241ec
  url: https://github.com/ctuning/artifact-evaluation
  cache: True
- alias: test-dummy3-clone-git-repo3
  task: clone-git-repo
  task_uid: af9422df6ea241ec
  url: https://github.com/ctuning/mlcommons-ck
  cache: True
